using System;
using System.Linq;
using System.Linq.Dynamic.Core;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using LostFound.AI.Core;
using LostFound.Matches.Dtos;

namespace LostFound.Matches
{
    public class MatchAppService : ApplicationService, IMatchAppService
    {
        private readonly IMatchRepository _matchRepository;
        private readonly MatchManager _matchManager;
        private readonly IEmbeddingEngine _embeddingEngine;
        private readonly IConfiguration _configuration;

        public MatchAppService(
            IMatchRepository matchRepository,
            MatchManager matchManager,
            IEmbeddingEngine embeddingEngine,
            IConfiguration configuration)
        {
            _matchRepository = matchRepository;
            _matchManager = matchManager;
            _embeddingEngine = embeddingEngine;
            _configuration = configuration;
        }

        // Mirrors ReportMatchingBackgroundJob's own threshold/provider-name
        // resolution exactly, so a manual recompute and the automatic
        // background-job path can never silently disagree on either value.
        public async Task<int> RecomputeMatchesAsync(Guid reportId)
        {
            var threshold = _configuration.GetValue<double?>("LostFound:AI:MatchThreshold") ?? 75;

            return await _matchManager.FindAndCreateMatchesAsync(reportId, threshold, _embeddingEngine.EngineName);
        }

        public async Task<PagedResultDto<MatchDto>> GetListAsync(PagedAndSortedResultRequestDto input)
        {
            var queryable = await _matchRepository.GetQueryableAsync();
            var totalCount = queryable.Count();
            var sorting = string.IsNullOrWhiteSpace(input.Sorting) ? "CreationTime desc" : input.Sorting;

            var matches = await AsyncExecuter.ToListAsync(
                queryable.OrderBy(sorting).Skip(input.SkipCount).Take(input.MaxResultCount)
            );

            return new PagedResultDto<MatchDto>(totalCount, matches.Select(MapToDto).ToList());
        }

        public async Task<MatchDto> AcceptAsync(Guid id)
        {
            var match = await _matchRepository.GetAsync(id);
            match.Accept();
            await _matchRepository.UpdateAsync(match);

            await _matchManager.NotifyMatchDecisionAsync(match, accepted: true);

            return MapToDto(match);
        }

        public async Task<MatchDto> RejectAsync(Guid id)
        {
            var match = await _matchRepository.GetAsync(id);
            match.Reject();
            await _matchRepository.UpdateAsync(match);

            await _matchManager.NotifyMatchDecisionAsync(match, accepted: false);

            return MapToDto(match);
        }

        private static MatchDto MapToDto(Match match)
        {
            return new MatchDto
            {
                Id = match.Id,
                CreationTime = match.CreationTime,
                LastModificationTime = match.LastModificationTime,
                LostReportId = match.LostReportId,
                FoundReportId = match.FoundReportId,
                SimilarityScore = match.SimilarityScore,
                MatchReason = match.MatchReason,
                Status = match.Status,
                IsAutoGenerated = match.IsAutoGenerated
            };
        }
    }
}
