using System;
using Volo.Abp.Domain.Entities.Auditing;

namespace LostFound.Matches
{
    public class Match : FullAuditedAggregateRoot<Guid>
    {
        public virtual Guid LostReportId { get; private set; }

        public virtual Guid FoundReportId { get; private set; }

        // 0-100 percentage (AI semantic similarity, text+image combined).
        public virtual decimal? SimilarityScore { get; private set; }

        public virtual string? MatchReason { get; private set; }

        public virtual MatchStatus Status { get; private set; }

        public virtual bool IsAutoGenerated { get; private set; }

        protected Match()
        {
        }

        public Match(
            Guid id,
            Guid lostReportId,
            Guid foundReportId,
            decimal? similarityScore,
            string? matchReason,
            MatchStatus status = MatchStatus.Pending,
            bool isAutoGenerated = false) : base(id)
        {
            LostReportId = lostReportId;
            FoundReportId = foundReportId;
            SimilarityScore = similarityScore;
            MatchReason = matchReason;
            IsAutoGenerated = isAutoGenerated;
            Status = status;
        }

        public Match Accept()
        {
            Status = MatchStatus.Accepted;
            return this;
        }

        public Match Reject()
        {
            Status = MatchStatus.Rejected;
            return this;
        }
    }
}
