using System;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Domain.Services;
using LostFound.Reports;
using LostFound.Matching;
using LostFound.Notifications;

namespace LostFound.Matches
{
    public class MatchManager : DomainService
    {
        private readonly IMatchRepository _matchRepository;
        private readonly IReportRepository _reportRepository;
        private readonly INotificationRepository _notificationRepository;

        public MatchManager(
            IMatchRepository matchRepository,
            IReportRepository reportRepository,
            INotificationRepository notificationRepository)
        {
            _matchRepository = matchRepository;
            _reportRepository = reportRepository;
            _notificationRepository = notificationRepository;
        }

        // Called by the background job AFTER the report's embedding has
        // already been generated and saved. Category plays NO role in
        // candidate selection or scoring. Text similarity always
        // contributes; image similarity is blended in (60/40) when BOTH
        // reports have an image embedding.
        public async Task<int> FindAndCreateMatchesAsync(
            Guid reportId,
            double thresholdPercentage,
            string providerNameForExplanation)
        {
            var report = await _reportRepository.GetAsync(reportId);

            var textEmbedding = report.GetEmbeddingVector();
            if (textEmbedding == null)
            {
                return 0;
            }

            var oppositeType = report.Type == ReportType.Lost ? ReportType.Found : ReportType.Lost;

            var candidates = await _reportRepository.GetMatchCandidatesAsync(report.Id, oppositeType);

            var createdCount = 0;

            foreach (var candidate in candidates)
            {
                var candidateTextEmbedding = candidate.GetEmbeddingVector();
                var textScore = CosineSimilarityCalculator.CalculatePercentage(textEmbedding, candidateTextEmbedding);

                double score = textScore;
                var imageEmbedding = report.GetImageEmbeddingVector();
                var candidateImageEmbedding = candidate.GetImageEmbeddingVector();

                if (imageEmbedding != null && candidateImageEmbedding != null)
                {
                    var imageScore = CosineSimilarityCalculator.CalculatePercentage(imageEmbedding, candidateImageEmbedding);
                    score = (textScore * 0.6) + (imageScore * 0.4);
                }

                if (score < thresholdPercentage)
                {
                    continue;
                }

                var lostReportId = report.Type == ReportType.Lost ? report.Id : candidate.Id;
                var foundReportId = report.Type == ReportType.Found ? report.Id : candidate.Id;

                if (await _matchRepository.ExistsForPairAsync(lostReportId, foundReportId))
                {
                    continue;
                }

                var explanation = MatchExplanationBuilder.Build(score, providerNameForExplanation);

                var match = new Match(
                    GuidGenerator.Create(),
                    lostReportId,
                    foundReportId,
                    (decimal)score,
                    explanation,
                    MatchStatus.Pending,
                    isAutoGenerated: true
                );

                await _matchRepository.InsertAsync(match);

                await NotifyBothReportersAsync(
                    match,
                    lostReportId == report.Id ? report : candidate,
                    foundReportId == report.Id ? report : candidate,
                    "Possible match found",
                    $"We found a possible match with {score:0.0}% confidence. Please review it."
                );

                createdCount++;
            }

            return createdCount;
        }

        public async Task NotifyMatchDecisionAsync(Match match, bool accepted)
        {
            var lostReport = await _reportRepository.GetAsync(match.LostReportId);
            var foundReport = await _reportRepository.GetAsync(match.FoundReportId);

            var title = accepted ? "Match accepted" : "Match rejected";
            var message = accepted
                ? "Your match was confirmed by the other party."
                : "Your match was rejected by the other party.";

            await NotifyBothReportersAsync(match, lostReport, foundReport, title, message);
        }

        private async Task NotifyBothReportersAsync(Match match, Report lostReport, Report foundReport, string title, string message)
        {
            await _notificationRepository.InsertAsync(
                new Notification(GuidGenerator.Create(), lostReport.ReporterId, lostReport.Id, title, message)
            );

            await _notificationRepository.InsertAsync(
                new Notification(GuidGenerator.Create(), foundReport.ReporterId, foundReport.Id, title, message)
            );
        }
    }
}
