using System;
using Volo.Abp.Application.Dtos;

namespace LostFound.Matches.Dtos
{
    public class MatchDto : AuditedEntityDto<Guid>
    {
        public Guid LostReportId { get; set; }
        public Guid FoundReportId { get; set; }
        public decimal? SimilarityScore { get; set; }
        public string? MatchReason { get; set; }
        public MatchStatus Status { get; set; }
        public bool IsAutoGenerated { get; set; }
    }
}
