using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace LostFound.AI
{
    // The AI-first replacement for manual Category selection. Given a
    // description and an optional image, returns everything the UI used to
    // ask the user for, generated automatically instead.
    public interface IItemClassificationProvider
    {
        string ProviderName { get; }

        Task<ItemClassificationResult> ClassifyAsync(
            string? description,
            byte[]? imageBytes,
            CancellationToken cancellationToken = default);
    }

    public class ItemClassificationResult
    {
        // Free-text category NAME (resolved/created via CategoryManager,
        // never a Guid the AI could not possibly know).
        public string? CategoryName { get; set; }

        public string? ObjectType { get; set; }

        public string? Color { get; set; }

        public string? Brand { get; set; }

        public string? Explanation { get; set; }
        public string? SearchReason { get; set; }
        public List<string> SearchKeywords { get; set; } = new();

        // The ONLY field later embedded for semantic search - a natural-language
        // paragraph generated by the classification provider, not a field
        // concatenation. Never used for structured matching (ObjectType/Color/
        // Brand/Tags already cover that).
        public string? SearchText { get; set; }


        public System.Collections.Generic.List<string> Tags { get; set; } = new();

        // Used to build the image embedding (caption-then-embed approach).
        public string? ImageCaption { get; set; }
    }
}
