namespace LostFound.AI
{
    // Bound from configuration section "LostFound:AI".
    public class AIProviderOptions
    {
        // Default = Gemini: free tier, hosted, supports both text embedding
        // and vision (image captioning + classification) out of the box.
        public string Provider { get; set; } = "Gemini";

        // Some providers (currently: DeepSeek) have no embeddings API at all.
        // When Provider is one of those, embeddings are generated by this
        // SEPARATE provider instead - defaults to "Gemini". Ignored for
        // providers that do have their own embeddings (Gemini/OpenAI/Ollama/
        // HuggingFace), where Provider is used for both classification,
        // explanation, AND embeddings as before.
        public string? EmbeddingProvider { get; set; }

        public GeminiOptions Gemini { get; set; } = new();
        public OllamaOptions Ollama { get; set; } = new();
        public HuggingFaceOptions HuggingFace { get; set; } = new();
        public OpenAIOptions OpenAI { get; set; } = new();
        public DeepSeekOptions DeepSeek { get; set; } = new();

        // PHASE-VALIDATION-08: the Local-First classification FALLBACK tier
        // (see ILocalClassificationProvider) - deliberately its own section,
        // separate from Ollama above. "Ollama" above is one of the
        // pluggable PRIMARY/remote providers selected via "Provider"; this
        // section configures the always-available local LLM tier that
        // ClassificationEngine falls back to regardless of which primary
        // provider is configured, so it must not be coupled to whichever
        // provider happens to also be named Ollama.
        public LocalLlmOptions LocalLlm { get; set; } = new();
    }

    public class GeminiOptions
    {
        public string ApiKey { get; set; } = string.Empty;

        public string? EmbeddingModel { get; set; }
        public string? TextModel { get; set; }
    }

    public class OllamaOptions
    {
        public string BaseUrl { get; set; } = "http://localhost:11434";
        public string Model { get; set; } = "nomic-embed-text";

        // Vision-capable model for image captioning/classification, e.g.
        // `ollama pull llava`.
        public string VisionModel { get; set; } = "llava";
    }

    // PHASE-VALIDATION-08 (Local LLM Classification Engine Evaluation &
    // Replacement): configures the local-first classification fallback's
    // LLM tier - a small instruction-tuned model served by a local Ollama
    // daemon, evaluated empirically against Qwen2.5-family, Phi-4 Mini and
    // Gemma 3 candidates on this workspace's real (CPU-only, ~16GB RAM)
    // hardware. See PHASE-VALIDATION-08-Local-LLM-Classification-Engine-
    // Evaluation-Replacement-Report.md for the full benchmark and the
    // reasoning behind the chosen default model.
    public class LocalLlmOptions
    {
        // Master switch: when false, the local fallback tier skips the LLM
        // entirely and goes straight to the rule-based engine (the
        // pre-PHASE-VALIDATION-08 behavior) - useful for environments where
        // no local LLM runtime is installed, or to isolate a regression.
        public bool Enabled { get; set; } = true;

        public string BaseUrl { get; set; } = "http://localhost:11434";

        // Text classification model. Chosen from real, measured benchmark
        // results (accuracy/latency/hallucination-rate/JSON-validity) - see
        // the Phase Validation 08 report's Model Comparison and Final
        // Recommendation sections. Configurable so a deployment can swap
        // models (e.g. to trade latency for accuracy) with no code change.
        public string Model { get; set; } = "qwen2.5:3b";

        // Vision-capable model for image-based classification (paired
        // vision-component architecture - see the report's Multimodal
        // Architecture Recommendation). Empty/null disables the image path
        // entirely; the provider then degrades to text-only classification
        // for image-only or image+text reports, exactly like the pre-
        // existing text-only local fallback did.
        public string? VisionModel { get; set; } = "moondream";

        // Per-request timeout for the LLM call itself. PHASE-VALIDATION-08
        // real-world finding: an initial 15s default caused genuine
        // production timeouts, because it only budgeted for warm inference
        // and ignored Ollama's cold-load cost - qwen2.5:3b's own cold load
        // alone measured up to ~15s in this workspace's benchmark, leaving
        // zero time for actual generation once the model had been idled
        // out (Ollama's default ~5 minute keep-alive). 45s comfortably
        // covers a cold load (up to ~23s measured for the heaviest
        // candidate, gemma3:4b) plus generation for the slower real cases
        // seen in testing, while still failing well before it would hang
        // indefinitely. This bounds the background-job path (which has no
        // external timeout of its own); the search-time path is separately
        // bounded by AiMatchingService's own 20s AiCallTimeout regardless
        // of this value, so raising this default does not weaken that path
        // - it only stops this provider from giving up before the daemon
        // even had a chance to respond.
        public int TimeoutSeconds { get; set; } = 45;
    }

    public class HuggingFaceOptions
    {
        public string ApiKey { get; set; } = string.Empty;
        public string Model { get; set; } = "sentence-transformers/all-MiniLM-L6-v2";
        public string ImageCaptionModel { get; set; } = "nlpconnect/vit-gpt2-image-captioning";

        // Hosted instruct/chat model used for the best-effort rich
        // classification path (see HuggingFaceClassificationProvider for the
        // honest limitations of this approach on HF's free tier). Set to
        // empty/null to skip the generative attempt entirely and always use
        // the original caption+zero-shot-category-only behavior.
        public string? InstructModel { get; set; } = "HuggingFaceH4/zephyr-7b-beta";
    }

    public class OpenAIOptions
    {
        public string ApiKey { get; set; } = string.Empty;
        public string Model { get; set; } = "text-embedding-3-small";
    }

    // NOTE: DeepSeek's public API is chat-completions only (OpenAI-compatible)
    // - it has no embeddings endpoint and no reliable public vision/image
    // input at the time this was written. DeepSeek is therefore only wired
    // for classification; embeddings fall back to
    // AIProviderOptions.EmbeddingProvider (default "Gemini") - see
    // LostFoundAiProvidersServiceCollectionExtensions. (Match explanations no
    // longer use any provider at all - see MatchExplanationGenerator.)
    public class DeepSeekOptions
    {
        public string ApiKey { get; set; } = string.Empty;
        public string BaseUrl { get; set; } = "https://api.deepseek.com/v1/";

        // "deepseek-chat" (general) or "deepseek-reasoner" (adds reasoning
        // traces - slower, not needed for this short classification/
        // explanation use case).
        public string ChatModel { get; set; } = "deepseek-chat";
    }
}
